package com.example.documentsummarizer

import android.content.Context
import android.database.Cursor
import android.net.Uri
import android.os.Environment
import android.provider.MediaStore
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*

object FileUtils {
    
    fun getFileName(context: Context, uri: Uri): String {
        var result: String? = null
        
        if (uri.scheme == "content") {
            val cursor: Cursor? = context.contentResolver.query(uri, null, null, null, null)
            cursor?.use {
                if (it.moveToFirst()) {
                    val nameIndex = it.getColumnIndex(MediaStore.Images.Media.DISPLAY_NAME)
                    if (nameIndex >= 0) {
                        result = it.getString(nameIndex)
                    }
                }
            }
        }
        
        if (result == null) {
            result = uri.path
            val cut = result?.lastIndexOf('/')
            if (cut != -1 && cut != null) {
                result = result?.substring(cut + 1)
            }
        }
        
        return result ?: "Unknown file"
    }
    
    fun getFileFromUri(uri: Uri): File {
        // Simplified version - in production, you'd need proper URI to File conversion
        return File(uri.path ?: "")
    }
    
    fun saveSummaryToFile(context: Context, summary: String) {
        try {
            // Create filename with timestamp
            val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
            val timestamp = sdf.format(Date())
            val filename = "summary_$timestamp.txt"
            
            // Get Downloads directory
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            val file = File(downloadsDir, filename)
            
            // Write summary to file
            FileWriter(file).use { writer ->
                writer.write("# Document Summary\n\n")
                writer.write("Generated: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}\n\n")
                writer.write(summary)
                writer.write("\n\n---\nGenerated by AI Document Summarizer")
            }
            
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    
    fun getFileSize(context: Context, uri: Uri): Long {
        val cursor = context.contentResolver.query(uri, null, null, null, null)
        return cursor?.use {
            if (it.moveToFirst()) {
                val sizeIndex = it.getColumnIndex(MediaStore.Images.Media.SIZE)
                if (sizeIndex >= 0) {
                    it.getLong(sizeIndex)
                } else 0L
            } else 0L
        } ?: 0L
    }
    
    fun isPDF(filename: String?): Boolean {
        return filename?.lowercase()?.endsWith(".pdf") == true
    }
}